name: AtomX Kernel
env:
      TOKEN: ${{ secrets.BOT_API_KEY }}
on:
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  atom-x-kernel:
    runs-on: ubuntu-latest
    container:
      image: atomxorg/ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Kernel Source
      run: /noclone3 bash init.sh
    - name: Start Compilation
      run: /noclone3 bash $HOME/kernel/asus.sh
